version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_voluntariado
    restart: always
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - voluntariado_net

volumes:
  mysql_data:

networks:
  voluntariado_net:
    driver: bridge
