name: CI/CD Frontend (React)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  # 1️⃣ Primero ejecuta el CI del backend
  check_backend_ci:
    name: Verificar CI del Backend
    uses: ./.github/workflows/CI.yml

  # 2️⃣ Luego el job del frontend
  ci_frontend:
    name: Test Frontend React
    runs-on: ubuntu-latest
    needs: check_backend_ci # ✅ Solo se ejecuta si el backend pasa correctamente

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar linting
        run: npm run lint || echo "Linting skipped"

      - name: Compilar y verificar (Build Check)
        run: npm run build

      - name: Subir Artifacto de Build
        uses: actions/upload-artifact@v4
        with:
          name: build-react-app
          path: ./frontend/build
          retention-days: 1
